// Table 5.1 of the PRD: which browser value selects which word list.
// Each row is [browser value, language code]. The codes come from the table, not from the files.
export const TABLE_5_1: ReadonlyArray<readonly [string, string]> = [
  ["en-gb", "en-GB"],
  ["en-ie", "en-GB"],
  ["en-au", "en-GB"],
  ["en-nz", "en-GB"],
  ["en-za", "en-GB"],
  ["en-in", "en-GB"],
  ["en", "en-US"],
  ["en-US", "en-US"],
  ["en-CA", "en-US"],
  ["de", "de"],
  ["de-DE", "de"],
  ["de-AT", "de"],
  ["fr-ca", "fr-CA"],
  ["fr", "fr-FR"],
  ["fr-FR", "fr-FR"],
  ["fr-BE", "fr-FR"],
  ["es", "es"],
  ["es-MX", "es"],
  ["it", "it"],
  ["it-CH", "it"],
  ["pt-br", "pt-BR"],
  ["pt", "pt-PT"],
  ["pt-PT", "pt-PT"],
  ["pt-AO", "pt-PT"],
  ["nl", "nl"],
  ["nl-BE", "nl"],
  ["sv", "sv"],
  ["sv-SE", "sv"],
  ["no", "nb"],
  ["no-NO", "nb"],
  ["nb", "nb"],
  ["nb-NO", "nb"],
  ["da", "da"],
  ["da-DK", "da"],
  ["fi", "fi"],
  ["fi-FI", "fi"],
  ["pl", "pl"],
  ["pl-PL", "pl"],
];

/** Cases of the FR-2 criterion that give a list of values. */
export const FR2_LISTS: ReadonlyArray<readonly [string[], string]> = [
  [["sv-SE", "en"], "sv"],
  [["xx"], "en-US"],
  [["PT-BR"], "pt-BR"],
  [["not a tag!", "de-AT"], "de"],
  [[], "en-US"],
  [["xx", "yy", "FR-CA"], "fr-CA"],
];
