// FR-47: the public styling API. `API.md` lists the same names (a test compares the two lists).

/** CSS custom properties. Set them on the `<hekate-generator>` element or on any parent. */
export const CSS_PROPERTIES = [
  "--hekate-font-family",
  "--hekate-password-font-family",
  "--hekate-password-font-size",
  "--hekate-color-text",
  "--hekate-color-text-quiet",
  "--hekate-color-surface",
  "--hekate-color-border",
  "--hekate-color-brand",
  "--hekate-color-on-brand",
  "--hekate-color-separator",
  "--hekate-color-number",
  "--hekate-color-symbol",
  "--hekate-color-digit",
  "--hekate-color-strength-weak",
  "--hekate-color-strength-fair",
  "--hekate-color-strength-strong",
  "--hekate-color-strength-very-strong",
  "--hekate-radius",
  "--hekate-gap",
] as const;

/** Part names for `hekate-generator::part(name)`. */
export const PARTS = [
  "base",
  "live-region",
  "error",
  "retry-button",
  "password",
  "token-word",
  "token-separator",
  "token-number",
  "token-symbol",
  "token-lower",
  "token-upper",
  "token-digit",
  "new-password-button",
  "copy-button",
  "copy-status",
  "strength",
  "strength-bar",
  "strength-label",
  "strength-info-button",
  "strength-details",
  "strength-details-close",
  "entropy",
  "crack-time",
  "crack-note",
  "strength-note",
  "naive-strength",
  "password-length",
  "options",
  "mode",
  "language",
  "words",
  "words-value",
  "separator",
  "capitalization",
  "number",
  "symbol",
  "ascii-only",
  "length",
  "length-value",
  "charsets",
  "charset",
  "avoid-similar",
  "no-repeat",
] as const;

/** Attributes of table 5.2. */
export const ATTRIBUTES = [
  "mode",
  "language",
  "words",
  "separator",
  "capitalization",
  "number",
  "symbol",
  "ascii-only",
  "length",
  "charsets",
  "avoid-similar",
  "no-repeat",
  "ui-language",
  "theme",
  "assets-url",
] as const;
