// Copies the few Font Awesome Free icons that Web Awesome needs from the
// Web Awesome 3.14.0 package into src/icons/fa-free.generated.ts.
// Run it again only when Web Awesome changes. Font Awesome Free icons use the
// CC BY 4.0 license: https://fontawesome.com/license/free
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const dist = join(dirname(require.resolve("@awesome.me/webawesome/package.json")), "dist");
const chunk = readFileSync(join(dist, "chunks/chunk.YPRC5XZF.js"), "utf8");
if (!chunk.includes("// src/components/icon/library.system.ts")) {
  throw new Error("Web Awesome changed: the system icon chunk moved. Update this script.");
}

const WANTED = {
  solid: ["check", "chevron-down", "xmark", "indeterminate"],
  regular: ["circle-xmark"],
};

function section(variant) {
  const start = chunk.indexOf(`  ${variant}: {`);
  if (start < 0) throw new Error(`no ${variant} icons`);
  const end = chunk.indexOf("\n  }", start);
  return chunk.slice(start, end);
}

const out = {};
for (const [variant, names] of Object.entries(WANTED)) {
  const text = section(variant);
  out[variant] = {};
  for (const name of names) {
    const re = new RegExp(`^    "?${name}"?: \`(<svg[^\\n]*</svg>)\`,?$`, "m");
    const match = text.match(re);
    if (!match) throw new Error(`icon ${variant}/${name} not found`);
    const svg = match[1].replace(/<!--[\s\S]*?-->/g, "");
    const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
    const body = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
    if (!viewBox) throw new Error(`icon ${name} has no viewBox`);
    out[variant][name] = { viewBox, body };
  }
}

const header = `// Generated by scripts/extract-icons.mjs. Do not edit.
// These icons are from Font Awesome Free (CC BY 4.0, https://fontawesome.com/license/free).
// They come from the Web Awesome 3.14.0 package, which includes them.
`;
writeFileSync(
  join(import.meta.dirname, "../src/icons/fa-free.generated.ts"),
  `${header}\nexport interface IconData {\n  viewBox: string;\n  body: string;\n}\n\nexport const FA_FREE: Record<string, Record<string, IconData>> = ${JSON.stringify(out, null, 2)};\n`,
);
