[package]
name = "hekate-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "wasm-bindgen API of Hekate"
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hekate-core = { path = "../hekate-core" }
rand_core = "0.10"
getrandom = { version = "0.4", features = ["wasm_js"] }
sha2 = { version = "0.11", default-features = false }
wasm-bindgen = "=0.2.129"

[dev-dependencies]
wasm-bindgen-test = "=0.3.79"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(hekate_node)'] }
